set up the menu icons for the posts
motuncoded/social_website pull request #16
Opened 2024-07-01 14:35 UTC by motuncoded

In this change, I set up the menu icons for the posts
closes #15

2024-07-01 16:55 UTC, Asylcreek requested changes
And your deployment failed, please check

2024-07-01 16:55 UTC, Asylcreek commented on pages/hooks/useFetchComments.ts
> +    queryKey: [queryKeys.GET_COMMENT],
Your function says `FetchComments` but your query key says `GET_COMMENT`.

I think that is a little confusing and/or misleading

2024-07-01 16:55 UTC, Asylcreek commented on pages/queryKeys.ts
> +  GET_USER: "get_user",
I think these should be all caps, the values. Because they are constants, and in JS world, we use CAPS_CAMEL_CASE to represent constants

2024-07-02 11:19 UTC, Asylcreek requested changes

2024-07-02 11:19 UTC, Asylcreek commented on pages/queryKeys.ts
> +  FETCH_COMMENTS: "FETCH_COMMENT",
```suggestion
  FETCH_COMMENTS: "FETCH_COMMENTS",
```

2024-07-02 11:19 UTC, Asylcreek commented on pages/queryKeys.ts
> +  FETCH_USERS: "FETCH_USER",
```suggestion
  FETCH_USERS: "FETCH_USERS",
```

2024-07-02 15:58 UTC, motuncoded commented on pages/queryKeys.ts
> +  FETCH_COMMENTS: "FETCH_COMMENT",
ok

2024-07-02 20:12 UTC, Asylcreek approved these changes

2024-07-02 23:20 UTC, merged