News page
motuncoded/social_website pull request #18
Opened 2024-07-05 20:53 UTC by motuncoded

In this change, I set up the news card

2024-07-07 17:37 UTC, Asylcreek requested changes

2024-07-07 17:37 UTC, Asylcreek commented on pages/queryKeys.ts
> +
Why?

2024-07-07 17:37 UTC, Asylcreek commented on pages/comments.tsx
> +import useFetchComments from "./hooks/useFetchComments"; // Adjust the path as necessary
```suggestion
import useFetchComments from "./hooks/useFetchComments"; 
```

2024-07-07 17:37 UTC, Asylcreek commented on pages/hooks/useFetchComments.ts
> +import { QueryKeys } from "../queryKeys"; // Adjust the import path as necessary
```suggestion
import { QueryKeys } from "../queryKeys";
```

2024-07-07 17:37 UTC, Asylcreek commented on pages/hooks/useFetchComments.ts
>    const COMMENTS_URL = "https://jsonplaceholder.typicode.com/comments";
This no longer needs to be in a variable

2024-07-07 17:37 UTC, Asylcreek commented on pages/hooks/useFetchNews.ts
> +// Adjust the import path as necessary
Delete this line

2024-07-07 17:37 UTC, Asylcreek commented on pages/hooks/useFetchNews.ts
> +  }
You should `try-catch` like this. ReactQuery would always return a success if you do. If you need to do stuff to the error, use the `onError` key that you can pass to `useQuery`

2024-07-07 17:37 UTC, Asylcreek commented on pages/hooks/useFetchUsers.ts
>    const USERS_URL = "https://jsonplaceholder.typicode.com/users";
This needs not be in a variable as it is only being used inside this function

2024-07-07 17:37 UTC, Asylcreek commented on pages/news.tsx
> +      className={`${poppins.className} flex justify-center items-center flex-col bg-[var(--main-bg-color-default)] text-[var(--main-color)] py-4`}
Shouldn't you load the `poppins` className in your layout file?

Also, setting the `poppins` className like this does not change the font-family of the element.

2024-07-10 19:44 UTC, Asylcreek requested changes

2024-07-10 19:44 UTC, Asylcreek commented on pages/_app.tsx
> +import Navbar from "./components/Navbar";
This doesn't appear to be used

2024-07-10 19:44 UTC, Asylcreek commented on pages/comments.tsx
> +function CommentsPage() {
Why did you change to using `function`?

2024-07-10 19:44 UTC, Asylcreek commented on pages/hooks/useFetchComments.ts
>    const COMMENTS_URL = "https://jsonplaceholder.typicode.com/comments";
You resolved this, but it actually isn't resolved yet

2024-07-10 19:44 UTC, Asylcreek commented on pages/hooks/useFetchNews.ts
> +  }
Throwing the error is equivalent to removing the `try-catch`

2024-07-10 19:44 UTC, Asylcreek commented on pages/hooks/useFetchUsers.ts
> +const USERS_URL = "https://jsonplaceholder.typicode.com/users";
Why are you saving this in a variable?

2024-07-10 19:44 UTC, Asylcreek commented on pages/news.tsx
> +import React from "react";
You do not need to import React here

2024-07-10 19:44 UTC, Asylcreek commented on pages/posts.tsx
> +import React from "react";
Why?

2024-07-10 19:44 UTC, Asylcreek commented on pages/posts.tsx
>  import { inter, roboto_serif } from "../styles/fonts";
Shouldn't all your font initialisations be inside your root layout file?

Or are you saying that it is only this page that would make use of the `Inter` and `Roboto` fonts?

2024-07-10 19:44 UTC, Asylcreek commented on pages/query-keys.ts
> +};
This type is not so necessary ... Typescript would infer the type of queryKeys as `Record<string, string>`

2024-07-10 19:44 UTC, Asylcreek commented on pages/users.tsx
>  import { inter } from "../styles/fonts";
This is the second place I am seeing this import, please check all your files that have font imports and move them into your root layout file.

PS. You can set up your next/fonts to use a CSS var, so you can just use that CSS var whenever you need to use that font.

2024-07-10 19:44 UTC, Asylcreek commented on pages/users.tsx
> +function UsersPage() {
Why did you change to using `function`?

2024-07-10 19:44 UTC, Asylcreek commented on tsconfig.json
> +    "pages/hooks/query-keys.ts"
Nope. Remove this.

Also, you should only have files/folders inside the `pages` directory that you want to translate to actual routes. We had this conversation during the weekend.

`/pages/hooks/query-keys.ts` tells Next that it should prepare a route with `/hooks/query-keys`, which I am confident that you do not want.

2024-07-11 04:53 UTC, motuncoded commented on pages/_app.tsx
> +import Navbar from "./components/Navbar";
I have remove it form the index .tsx instead

2024-07-12 08:10 UTC, Asylcreek requested changes

2024-07-12 08:10 UTC, Asylcreek commented on pages/news.tsx
>  import { poppins } from "../styles/fonts";
I am not expecting this here

2024-07-12 08:10 UTC, Asylcreek commented on pages/news.tsx
>  import { poppins } from "../styles/fonts";
You can (and should) create a layout component that imports all your fonts and attaches them to the DOM.

Not like this

2024-07-15 09:19 UTC, Asylcreek approved these changes

2024-07-15 21:31 UTC, merged