Create a simple scroll of posts
motuncoded/social_website pull request #4
Opened 2024-06-07 16:34 UTC by motuncoded

In this feature, I  used Posts Placeholder API which  render a simple scroll of different posts from the top to the end of the posts.

Resolves #3

2024-06-07 22:26 UTC, Asylcreek requested changes
Please install Prettier

2024-06-07 22:26 UTC, Asylcreek commented on pages/index.tsx
> +  };
Move these outside the React function

2024-06-08 07:42 UTC, iamr0b0tx commented
> Please install Prettier

This is the second time I have seen this comment.

I think the first was because you didn't install prettier; this one is because you did not run the prettier formatter before pushing this change.

I advise you to set up a hook to ensure your file gets formatted when you change. An example will be an on-save hook, it formats the file when you save it, some IDEs support this. 

Another option will be a pre-commit hook, I don't like this one because I think formatting changes should be reviewed before committing. There are a few ways around this. You can set prettier in your pre-commit hook such that it raises an error when it sees unformatted code, that way when you try to commit it will fail and tell you it is because it found unformatted code. In that case, you can then run the formatter, review the changes, add it and then try committing again. 

__PLEASE ENSURE YOU READ THIS MESSAGE MULTIPLE TIMES AND UNDERSTAND WHAT I AM SAYING, I WOULD HATE TO HAVE TO REPEAT MYSELF__. Hope it helps

2024-06-08 11:38 UTC, motuncoded commented on pages/index.tsx
> +  };
Ok

2024-06-08 13:19 UTC, Asylcreek approved these changes
Please deploy, so I can see live previews

2024-06-08 20:31 UTC, iamr0b0tx approved these changes

2024-06-09 09:40 UTC, merged