Infinite scroll of posts
motuncoded/social_website pull request #6
Opened 2024-06-09 14:27 UTC by motuncoded

In this change, I created a Posts.tsx file that can allow infinite scroll of posts with loading when navigating down the posts.

closes #5

2024-06-09 19:23 UTC, Asylcreek requested changes

2024-06-09 19:23 UTC, Asylcreek commented on pages/Posts.tsx
> +type PageNumber = number;
You did not need to create a type alias for this.

Typing line 26 as `number` would have been enough

2024-06-09 19:23 UTC, Asylcreek commented on pages/Posts.tsx
> +  const [hasMore, setHasMore] = useState(true);
I don't think `true` should be the default

2024-06-09 19:23 UTC, Asylcreek commented on pages/Posts.tsx
> +      }
Flip this condition around

2024-06-09 19:23 UTC, Asylcreek commented on pages/Posts.tsx
> +      document.documentElement.scrollHeight
Shouldn't these be `document.body` instead?

2024-06-09 19:23 UTC, Asylcreek commented on pages/Posts.tsx
> +  const handleScroll = () => {
Move this function inside the useEffect below

2024-06-09 19:23 UTC, Asylcreek commented on pages/Posts.tsx
> +  });
```suggestion
  }, []);
```

2024-06-11 06:52 UTC, Asylcreek approved these changes, later dismissed

2024-06-11 06:54 UTC, Asylcreek commented on pages/Posts.tsx
Why did you create this in a separate file?

Do you realize that `/` and `/posts` would practically be showing the same things?

2024-06-11 09:37 UTC, motuncoded commented on pages/Posts.tsx
ok

2024-06-11 09:40 UTC, motuncoded commented on pages/Posts.tsx
I noticed that the posts rendered twice according to id and I have been trying to fix it and it seems unattainable, can you please recommend something
![copt](https://github.com/motuncoded/social_website/assets/67984447/e3472246-1eb0-43c6-868a-43dbbd230112)

2024-06-12 07:05 UTC, Asylcreek commented on pages/Posts.tsx
What exactly do you want to happen?

Which route do you want your users to access posts from?

2024-06-12 07:06 UTC, Asylcreek approved these changes

2024-06-12 14:29 UTC, merged